
name: Install dotfiles
on: [ push, pull_request, workflow_dispatch ] 

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install
        run: ./linux/install.sh
